version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgressql/data
    ports:
      - "5432:5432"
  api:
    build: 
      context: .
      dockerfile: dockerfile
    container_mame: bookstore-api
    ports:
      - "8000:8000"
